### ISSUE TITLE
WaterDog Error

### ISSUE THREAD

**Issue by Obamavn99** [yesdog/Waterdog#101]
ater: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #12/INFO]: [Toan31] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #12/INFO]: [quiludan] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #3/INFO]: [Nhanvnfca1212] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #9/INFO]: [GoGoBeDe] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #9/INFO]: [TLGM2308] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
[13:38:43] [Netty Worker IO Thread #0/INFO]: [/123.21.156.105:49989|yennhi2906] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #9/INFO]: [/14.187.11.1:45318|SimMinYuu] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #0/INFO]: [/171.236.79.66:32874|SecondWord13430] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #3/INFO]: [/14.176.162.154:36035|Nhanvnfca1212] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #9/INFO]: [/113.184.143.188:46284|TLGM2308] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #12/INFO]: [/14.242.116.47:38053|quiludan] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #3/INFO]: [/115.78.119.121:51335|AXC990] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #3/INFO]: [/171.225.137.63:40155|Yuu5743] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #9/INFO]: [/42.112.89.205:55233|GoGoBeDe] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #1/INFO]: [/115.78.119.121:50007|AXC989] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #0/INFO]: [/14.163.211.102:56756|ThermicOrca4257] -> UpstreamBridge has disconnected
[13:38:43] [Netty Worker IO Thread #12/INFO]: [/27.3.112.144:35544|Toan31] -> UpstreamBridge has disconnected
[13:38:44] [Netty Worker IO Thread #6/INFO]: [/1.54.124.30:32468|HeadyKibbles957] -> UpstreamBridge has disconnected
[13:38:44] [Netty Worker IO Thread #1/INFO]: [/27.74.65.223:35961|Noob_LH] -> UpstreamBridge has disconnected
[13:38:47] [Netty Worker IO Thread #0/ERROR]: [DuyVN2004|/42.118.177.150:64626] <-> ServerConnector [lobby] - encountered exception
java.lang.ClassCastException: class network.ycc.raknet.packet.ServerHandshake cannot be cast to class net.md_5.bungee.protocol.PacketWrapper (network.ycc.raknet.packet.ServerHandshake and net.md_5.bungee.protocol.PacketWrapper are in unnamed module of loader 'app')
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:96) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:fa600ba:303]

**Comment by BRadHoc** [comment]
Expiriencing the same, can't connect to the default server. Tried localhost 127.0.0.1 the external IP. Few different port numbers, forced_default true and false
