### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by majovec** [yesdog/Waterdog#105]
**Version of Waterdog**
This server is running Waterdog version git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304 by md_5

**Expected Behavior**

**Actual Behavior**

**Crashdump, Backtrace or Other Files**

**Describe the bug**
Crash with connect mc client 1.14.60

**Server software used:**
PocketMine

**Additional context**

`[04:26:23 INFO]: [Amater235399|/46.135.108.233:2547] <-> ServerConnector [lobby] has connected
[04:26:24 ERROR]: [/46.135.108.233:2547|Amater235399] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(155882) + length(4) exceeds writerIndex(155882): PooledUnsafeDirectByteBuf(ridx: 155882, widx: 155882, cap: 155898)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1495) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:832) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at net.md_5.bungee.entitymap.EntityMap_PE.doRewrite(EntityMap_PE.java:151) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at net.md_5.bungee.entitymap.EntityMap_PE.rewriteClientbound(EntityMap_PE.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:119) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:142) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:112) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.pipeline.DisconnectHandler.channelRead(DisconnectHandler.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.packet.FrameSet.lambda$createFrames$5(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_232]
        at network.ycc.raknet.packet.FrameSet.createFrames(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.pipeline.ReliabilityHandler.readFrameSet(ReliabilityHandler.java:138) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.pipeline.ReliabilityHandler.channelRead(ReliabilityHandler.java:101) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.client.channel.RakNetClientChannel$ClientHandler.channelRead(RakNetClientChannel.java:108) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:154) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at network.ycc.raknet.channel.DatagramChannelProxy$ListenerInboundProxy.channelRead(DatagramChannelProxy.java:371) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.epoll.EpollDatagramChannel.connectedRead(EpollDatagramChannel.java:572) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.epoll.EpollDatagramChannel.access$000(EpollDatagramChannel.java:57) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:505) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:394) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:388) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:bc8a3a5:304]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[04:26:24 INFO]: [Amater235399] disconnected with: The server you were previously on went down, you have been connected to a fallback server
`

**Comment by Alemiz112** [comment]
Are you running latest version of server and proxy?

**Comment by majovec** [comment]
yes

**Comment by TobiasG-DE** [comment]
The Build is working just fine on NetherGames on Production, so this is most likely not an issue on our side

**Comment by TobiasG-DE** [comment]
Closed due to inactivity. Author is free to reopen the issue.
