### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by strich3** [yesdog/Waterdog#130]
[13:14:53 WARN]: Event ConnectionInitEvent(remoteAddress=/192.168.178.41:65469, listener=ListenerInfo(socketAddress=/0.0.0.0:19132, motd=Another Bungee server, maxPlayers=1, tabListSize=60, serverPriority=[lobby], forceDefault=false, forcedHosts={pvp.md-5.net=pvp}, tabListType=GLOBAL_PING, setLocalAddress=true, pingPassthrough=false, queryPort=19132, queryEnabled=true, proxyProtocol=false, rakNet=true), isCancelled=false) took 347ms to process!
[13:14:54 INFO]: [/192.168.178.41:65469] <-> InitialHandler has connected
[13:14:54 ERROR]: [/192.168.178.41:65469|strich_4] <-> InitialHandler - encountered exception
java.lang.UnsatisfiedLinkError: 'void net.md_5.bungee.jni.cipher.NativeCipherImpl.staticPEHash(long, long, int, long, long)'
        at net.md_5.bungee.jni.cipher.NativeCipherImpl.staticPEHash(Native Method) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at net.md_5.bungee.jni.cipher.NativeCipher.staticPEHash(NativeCipher.java:124) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.waterdog.pe.PENativeExt.staticPEHash(PENativeExt.java:62) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.waterdog.pe.PEEncryptionInitializer.createHash(PEEncryptionInitializer.java:203) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.waterdog.pe.PEEncryptionInitializer.createHash(PEEncryptionInitializer.java:197) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.waterdog.pe.PEEncryptionInitializer$PECipherDecoder.channelRead(PEEncryptionInitializer.java:125) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.server.pipeline.ConnectionInitializer$RestartConnectionHandler.channelRead(ConnectionInitializer.java:161) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.pipeline.DisconnectHandler.channelRead(DisconnectHandler.java:27) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.packet.FrameSet.lambda$createFrames$5(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at network.ycc.raknet.packet.FrameSet.createFrames(FrameSet.java:166) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.pipeline.ReliabilityHandler.readFrameSet(ReliabilityHandler.java:138) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.pipeline.ReliabilityHandler.channelRead(ReliabilityHandler.java:101) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at network.ycc.raknet.server.channel.RakNetServerChannel$ServerHandler.lambda$channelRead$2(RakNetServerChannel.java:133) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4088b94:4]
        at java.lang.Thread.run(Thread.java:834) [?:?]

--------------

Was habe ich falsch gemacht!?

Version: 1.16
Altay

**Comment by strich3** [comment]
Can anyone help me!?

**Comment by Alemiz112** [comment]
When does this happen? Looks like client can not communicate with proxy and the connection fails.

**Comment by strich3** [comment]
I want to Join my Lobby Server (Software Altay)

**Comment by strich3** [comment]
My Config:

groups:
  md_5:
  - admin
bedrock_encryption: true
disabled_commands:
- disabledcommandhere
use_xuid_for_uuid: true
timeout: 30000
online_mode: true
servers:
  lobby:
    raknet: false
    motd: '&1Just another Waterfall - Forced Host'
    transfer_group: default
    address: localhost:25565
    restricted: false
server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: &id036
    pvp.md-5.net: pvp
  ping_passthrough: false
  raknet: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
- query_port: 19132
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts: *id036
  ping_passthrough: false
  raknet: true
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:19132
  max_players: 1
  tab_size: 60
  force_default_server: false
stats: 3d3a1434-e38c-40bc-962f-883108972a9c
network_compression_threshold: 256
log_pings: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
max_mtu: -1
ip_forward: false
player_limit: -1
log_commands: false
connection_throttle_limit: 3
connection_throttle: 4000
replace_username_spaces: true
prevent_proxy_connections: false
remote_ping_timeout: 5000
forge_support: true
remote_ping_cache: -1

Is the Config OK?

**Comment by Alemiz112** [comment]
I would say, it is caused by Altay. I have not tested WD with Altay. Also you do not need to have 2 listeners in proxy config. You can remove MC Java one (with port `25577`). 
Test if disabling encryption will help.

**Comment by strich3** [comment]
It says this... I changed the config

[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:142)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
[20:03:27 ERROR]:       at org.yaml.snakeyaml.Yaml.load(Yaml.java:453)
[20:03:27 ERROR]:       at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:80)
[20:03:27 ERROR]:       ... 6 more

**Comment by Alemiz112** [comment]
It looks like you have wrongly edited config.

**Comment by FlussRaplay** [comment]
Over all raknet: true

**Comment by Alemiz112** [comment]
Closing due to inactivity.
