### ISSUE TITLE
Error while connecting to mcpe server

### ISSUE THREAD

**Issue by TobiasG-DE** [yesdog/Waterdog#16]
This error is occuring in console: 
`[12:50:07 ERROR]: [TobiasDev|/217.246.57.158:49335] <-> ServerConnector [lobby] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(4082) exceeds writerIndex(2048): PooledUnsafeDirectByteBuf(ridx: 24, widx: 2048, cap: 2048)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.pipeline.FlushTickHandler.channelRead(FlushTickHandler.java:33) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.client.channel.RakNetClientChannel$ClientHandler.channelRead(RakNetClientChannel.java:104) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.channel.DatagramChannelProxy$ListenerInboundProxy.channelRead(DatagramChannelProxy.java:342) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:513) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:382) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(4082) exceeds writerIndex(2048): PooledUnsafeDirectByteBuf(ridx: 24, widx: 2048, cap: 2048)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1411) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.buffer.AbstractByteBuf.readRetainedSlice(AbstractByteBuf.java:880) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.frame.FrameData.read(FrameData.java:54) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.frame.Frame.read(Frame.java:62) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.packet.FrameSet.read(FrameSet.java:48) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.config.DefaultCodec.decode(DefaultCodec.java:105) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.pipeline.RawPacketCodec.decode(RawPacketCodec.java:35) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at network.ycc.raknet.pipeline.RawPacketCodec.decode(RawPacketCodec.java:13) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:cb9b897:183]
        ... 32 more`

Screen popping up when trying to join: http://prntscr.com/nt5njd

**Comment by colinrgodsey** [comment]
Should be fixed now. Reopen if its not
