### ISSUE TITLE
Random exceptions

### ISSUE THREAD

**Issue by Artuto** [yesdog/Waterdog#17]
Been getting some exceptions lately that look like this:

```
[18:15:36 ERROR]: [/:61270] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(4036) exceeds writerIndex(2048): PooledUnsafeDirectByteBuf(ridx: 24, widx: 2048, cap: 2048)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.pipeline.FlushTickHandler.channelRead(FlushTickHandler.java:41) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:350) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(24) + length(4036) exceeds writerIndex(2048): PooledUnsafeDirectByteBuf(ridx: 24, widx: 2048, cap: 2048)
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1411) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.buffer.AbstractByteBuf.readRetainedSlice(AbstractByteBuf.java:880) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.frame.FrameData.read(FrameData.java:54) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.frame.Frame.read(Frame.java:62) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.packet.FrameSet.read(FrameSet.java:48) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.config.DefaultCodec.decode(DefaultCodec.java:101) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.pipeline.RawPacketCodec.decode(RawPacketCodec.java:35) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at network.ycc.raknet.pipeline.RawPacketCodec.decode(RawPacketCodec.java:13) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[WaterLand.jar:git:WaterLand-Bootstrap:1.14-SNAPSHOT:8df1dd9:21]
... 22 more```

**Comment by TobiasG-DE** [comment]
#GotFixed

**Comment by colinrgodsey** [comment]
Should be fixed now. Reopen if its not
