### ISSUE TITLE
Bedrock Encryption does not work

### ISSUE THREAD

**Issue by KCodeYT** [yesdog/Waterdog#42]
When I join with ``bedrock_encryption: true`` in the config then this error comes

[20:15:15 ERROR]: [/127.0.0.1:62683|KCodeYT] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.raknet.pipeline.DisconnectHandler.channelRead(DisconnectHandler.java:28) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.raknet.packet.FrameSet.lambda$createFrames$4(FrameSet.java:149) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_211]
        at network.ycc.raknet.packet.FrameSet.createFrames(FrameSet.java:149) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.raknet.pipeline.ReliabilityHandler.readFrameSet(ReliabilityHandler.java:149) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.raknet.pipeline.ReliabilityHandler.channelRead(ReliabilityHandler.java:112) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.raknet.pipeline.FlushTickHandler.channelRead(FlushTickHandler.java:48) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:350) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.UnsupportedOperationException
        at io.netty.buffer.PooledHeapByteBuf.memoryAddress(PooledHeapByteBuf.java:334) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.waterdog.jni.JavaHash.staticPEHash(JavaHash.java:60) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.waterdog.pe.PEEncryptionInitializer.createHash(PEEncryptionInitializer.java:158) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.waterdog.pe.PEEncryptionInitializer$PECipherDecoder.decode(PEEncryptionInitializer.java:120) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at network.ycc.waterdog.pe.PEEncryptionInitializer$PECipherDecoder.decode(PEEncryptionInitializer.java:99) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:7d83123:240]
        ... 68 more

**Comment by colinrgodsey** [comment]
fixed in https://github.com/yesdog/Waterdog/commit/8508237b0943bf238b568da895d946123fa643e7
