### ISSUE TITLE
bosbar with pspe and waterdog error

### ISSUE THREAD

**Issue by WesleyVanNeck** [yesdog/Waterdog#5]
on join i get larg error latest build here is the error

[error bosbar pspe with waterdog.txt](https://github.com/yesdog/Waterdog/files/3120408/error.bosbar.pspe.with.waterdog.txt)

**Comment by WesleyVanNeck** [comment]
btw am using psps also for the bosbar this is what am using https://github.com/WesleyVanNeck/ProtocolSupportPocketStuff/commits/patch-1

**Comment by WesleyVanNeck** [comment]
edit i fixed that error now the bosbar wont show up

**Comment by WesleyVanNeck** [comment]
[10:44:02 ERROR]: [/31.20.200.143:55835|insaneboy101] <-> DownstreamBridge <-> [lobby] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class BossBar with contents:
+-------------------------------------------------+
| 0 1 2 3 4 5 6 7 8 9 a b c d e f |
+--------+-------------------------------------------------+----------------+
|00000000| 4a 9a 8d b2 e3 da a1 f3 c2 d1 01 00 |J........... |
+--------+-------------------------------------------------+----------------+
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:93) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledSlicedByteBuf(ridx: 12, widx: 12, cap: 12/12, unwrapped: PooledUnsafeDirectByteBuf(ridx: 246, widx: 448, cap: 32768))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:227) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:217) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:107) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.packet.BossBar.read(BossBar.java:42) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:71) ~[waterfall.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:2fabe41:112]
... 25 more

**Comment by WesleyVanNeck** [comment]
still there tested with a other plugin

**Comment by WesleyVanNeck** [comment]
spigot error:



`[07:44:30]

 [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Die Verbindung wurde vom Kommunikationspartner zurÃ¼ckgesetzt
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_201]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.write(IOUtil.java:51) ~[?:1.8.0_201]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471) ~[?:1.8.0_201]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:403) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:360) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
	at net.minecraft.server.v1_13_R2.NetworkManager.lambda$b$4(NetworkManager.java:214) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:310) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
[07:44:30] [Netty Server IO #0/WARN]: [io.netty.channel.AbstractChannelHandlerContext] An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
[07:44:30] [Netty Server IO #0/INFO]: ERROR IN PS. MOST LIKELY ROOT CAUSE:
`

**Comment by WesleyVanNeck** [comment]
@colinrgodsey plz help
