### ISSUE TITLE
Incompatibility with plugin messages in PE

### ISSUE THREAD

**Issue by Artuto** [yesdog/Waterdog#6]
Some plugins on the bukkit side are blowing up when a player connects to the server and they try to receive a plugin message from bungeecord.

Some examples are premium vanish and CMI:

```
> [23:02:43 WARN]: java.io.EOFException
> [23:02:43 WARN]: at java.io.DataInputStream.readFully(DataInputStream.java:197)
> [23:02:43 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:609)
> [23:02:43 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:564)
> [23:02:43 WARN]: at de.myzelyam.premiumvanish.bukkit.BukkitPluginMessageMgr.onPluginMessageReceived(BukkitPluginMessageMgr.java:61)
> [23:02:43 WARN]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
> [23:02:43 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [23:02:43 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
> [23:02:43 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
> [23:02:43 WARN]: at java.lang.Thread.run(Thread.java:748)
> [23:02:43 WARN]: [CMI] Plugin CMI v8.5.4.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:48) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_202]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
... 14 more
> [23:02:43 WARN]: [CMI] Plugin CMI v8.5.4.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:48) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_202]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
... 14 more
> [23:02:43 WARN]: [CMI] Plugin CMI v8.5.4.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:48) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_202]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
... 14 more
> [23:02:44 WARN]: [CMI] Plugin CMI v8.5.4.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:48) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_202]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_202]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.io.EOFException
at java.io.DataInputStream.readFully(DataInputStream.java:197) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_202]
at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_202]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.13.2.jar:git-Paper-"95e5ff5e"]
... 14 more
> [23:03:32 WARN]: java.io.EOFException
> [23:03:32 WARN]: at java.io.DataInputStream.readFully(DataInputStream.java:197)
> [23:03:32 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:609)
> [23:03:32 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:564)
> [23:03:32 WARN]: at de.myzelyam.premiumvanish.bukkit.BukkitPluginMessageMgr.onPluginMessageReceived(BukkitPluginMessageMgr.java:61)
> [23:03:32 WARN]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2624)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
> [23:03:32 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [23:03:32 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
> [23:03:32 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
> [23:03:32 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by colinrgodsey** [comment]
Fixed in https://github.com/yesdog/Waterdog/commit/81dfe15f731c1f565c9e7d75d2cb733aeca5c5cc    make sure to get the PSPE update here: https://github.com/ProtocolSupport/ProtocolSupport/pull/1080  so we can get all servers on the same page as far as format.
