### ISSUE TITLE
Error on Join since last Build

### ISSUE THREAD

**Issue by chaosfreak93** [yesdog/Waterdog#66]
[15:57:19] [Netty Worker IO Thread #0/INFO]: [/ip:51711] <-> InitialHandler has connected
[15:57:19] [Netty Worker IO Thread #0/ERROR]: [/ip:51711] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:753) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:778) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:747) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:801) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:88) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at net.md_5.bungee.netty.ChannelWrapper$2.run(ChannelWrapper.java:120) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.Protocol$ProtocolData.access$600(Protocol.java:496) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:555) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at net.md_5.bungee.protocol.MinecraftEncoder.acceptOutboundMessage(MinecraftEncoder.java:32) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:102) ~[waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
	... 16 more

**Comment by colinrgodsey** [comment]
Not enough info. Please reopen or recreate this using the template.
