### ISSUE TITLE
Error - Can't join over 1.13

### ISSUE THREAD

**Issue by iTzVeptionHD** [yesdog/Waterdog#68]
[10:50:11 INFO]: [/95.222.24.251:6908] <-> InitialHandler has connected
[10:50:11 ERROR]: [/95.222.24.251:6908] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:753) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:778) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:747) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:801) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at net.md_5.bungee.netty.ChannelWrapper$2.run(ChannelWrapper.java:120) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.md_5.bungee.protocol.Protocol$ProtocolData.access$600(Protocol.java:496) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:555) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at net.md_5.bungee.protocol.MinecraftEncoder.acceptOutboundMessage(MinecraftEncoder.java:32) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:a6c5dac:281]
        ... 16 more

**Comment by TobiasG-DE** [comment]
This is a problem with the current version. We are aware that this can happen and we are currently working on a solution. Unluckily, we have literally no documentation, so it may take some time

**Comment by GamakCZ** [comment]
Bedrock Dedicated Server still has symbols, so you can look in it using IDA, or you can look to Nukkit for changes.

**Comment by LymmyHD** [comment]
I can not Code in Java.

**Comment by GamakCZ** [comment]
https://github.com/FoxelTeam/Foxel last solution

**Comment by LymmyHD** [comment]
https://github.com/NetherGamesMC/PocketMine-MP and i use this Version of pmmp

**Comment by chenjy0812** [comment]
I had the same problem.

**Comment by TobiasG-DE** [comment]
_**We are aware that 1.13 is not working yet. We are still facing several issues with it. Please just wait for us to update, we'll announce it then.** _

**Comment by colinrgodsey** [comment]
fixed in https://ci.codemc.io/job/yesdog/job/Waterdog/285/
