### ISSUE TITLE
Unable to connect lobby suit

### ISSUE THREAD

**Issue by 664836965** [yesdog/Waterdog#91]
My English is not good, so I am very sorry to use a machine to translate the following content.
When I configure the waterdog to enter the lobby and the initialhandler-add exception is displayed, what should I do to resolve the problem thank you
this is my vps and config.yml
![Screenshot_2020-02-08-01-45-50-74](https://user-images.githubusercontent.com/52337544/74054025-1d54f900-4a18-11ea-8cdb-81df76ed5bc0.png)
![Screenshot_2020-02-08-00-55-32-04](https://user-images.githubusercontent.com/52337544/74054040-234ada00-4a18-11ea-959d-cccbb2b2bd27.png)

**Comment by 664836965** [comment]
this is my latest.log
 [Netty Worker IO Thread #0/INFO]: [/58.248.30.202:3079] <-> InitialHandler has connected
[11:08:24] [Netty Worker IO Thread #0/ERROR]: [/58.248.30.202:3079] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:753) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:778) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:747) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:801) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper$2.run(ChannelWrapper.java:120) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.Protocol$ProtocolData.access$500(Protocol.java:444) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:503) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.MinecraftEncoder.acceptOutboundMessage(MinecraftEncoder.java:32) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	... 16 more
[11:08:36] [Netty Worker IO Thread #1/INFO]: [/58.248.30.202:3079] <-> InitialHandler has connected
[11:08:36] [Netty Worker IO Thread #1/ERROR]: [/58.248.30.202:3079] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:753) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:778) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:747) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:801) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper$2.run(ChannelWrapper.java:120) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.Protocol$ProtocolData.access$500(Protocol.java:444) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:503) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.MinecraftEncoder.acceptOutboundMessage(MinecraftEncoder.java:32) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	... 16 more
[11:09:08] [Netty Worker IO Thread #2/INFO]: [/58.248.30.202:3079] <-> InitialHandler has connected
[11:09:08] [Netty Worker IO Thread #2/ERROR]: [/58.248.30.202:3079] <-> InitialHandler - encountered exception
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:753) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:778) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:747) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:801) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.netty.ChannelWrapper$2.run(ChannelWrapper.java:120) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.Protocol$ProtocolData.access$500(Protocol.java:444) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.Protocol$DirectionData.hasPacket(Protocol.java:503) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at net.md_5.bungee.protocol.MinecraftEncoder.acceptOutboundMessage(MinecraftEncoder.java:32) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.14-SNAPSHOT:987df34:255]
	... 16 more

**Comment by colinrgodsey** [comment]
It looks like you are trying to connect to Java Edition servers. Waterdog does not translate the protocols. The servers need to support Bedrock protocol (such as Nukkit, PMMP, etc)
