### ISSUE TITLE
Handle player disconnecting errors

### ISSUE THREAD

**Issue by Alemiz112** [yesdog/Waterdog#98]
We should try to handle and fix errors from this list. All errors are randomly appearing.

- *Too big packet*
```
[14:38:57 ERROR]: [/84.245.121.127:57693|alemiz003] -> UpstreamBridge - encountered exception
io.netty.handler.codec.DecoderException: Too big packet loss: ack confirm range
        at network.ycc.raknet.utils.Constants.packetLossCheck(Constants.java:14) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at network.ycc.raknet.pipeline.ReliabilityHandler.readAck(ReliabilityHandler.java:155) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at network.ycc.raknet.pipeline.ReliabilityHandler.channelRead(ReliabilityHandler.java:97) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at network.ycc.raknet.server.channel.RakNetServerChannel$ServerHandler.lambda$channelRead$2(RakNetServerChannel.java:133) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:388) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```
- *ReadTimeoutException*
Player is sometime disconnected due to timeout even if it is not true.
- *Tag type id must be greater than 0 and less than 12*
In `PELogin` while decoding block palette or when switching server and encoding palette (sometimes).
```
Caused by: java.lang.IndexOutOfBoundsException: Tag type id must be greater than 0 and less than 12        at com.nukkitx.nbt.TagType.byId(TagType.java:44) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at com.nukkitx.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:30) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at com.nukkitx.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:22) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]        at network.ycc.waterdog.pe.packet.PELogin.read(PELogin.java:150) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at net.md_5.bungee.protocol.DefinedPacket.read0(DefinedPacket.java:284) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:65) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:4d82b3f:12]
```

- *FrameDecoder is missing*
```
java.util.NoSuchElementException: frame-decoder
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1084) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:516) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at network.ycc.waterdog.pe.PEPipelineUtils$1.initChannel(PEPipelineUtils.java:75) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:953) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterdog.jar:git:Waterdog-Bootstrap:1.15-SNAPSHOT:f8841ce:unknown]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]```

**Comment by TobiasGrether** [comment]
Haven't seen any of those issues in a long time. If it happens, we might wanna create a milestone and an issue on the new repo
